### ISSUE TITLE
Street lamp builder tool

### ISSUE THREAD

**Issue by akosgarai** [akosgarai/playground_engine#103]
I want to implement a builder tool for the streetlamp model. It supposed to follow the same logic as the previous builders.

## Tasks

- [ ] Move streetlamp tests from the model tests file to a new streetlamp test file.
- [ ] Implement the builder tool.
- [ ] Tests for the builder tool.
- [ ] Make the original streetlamp constructor logic deprecated, remove it from the codebase.
