### ISSUE TITLE
Build wasm application

### ISSUE THREAD

**Issue by akosgarai** [akosgarai/playground_engine#148]
I want to be able to build a webassembly application to execute the animations in the browser.

## Must have a wrapper for the webgl calls

Something like:
- https://github.com/nuberu/webgl/blob/master/rendering_context.go - syscall/js

## Wrapper interface extension.

- The wrapper package has to be changed. It should contain the rendering target (window or canvas). Application could receive the same info from the wrapper.

## Window interface

- Currently the window interface depends on glfw. It has to be changed to internal types that could be reused on the wasm.
- Application uses the window interface as window. Instead of window, it supposed to be RenderingContext / RenderingTarget or something like it.

## Application package

- Currently it depends on glfw. It is unnecessary for wasm. (KeyCallback, MouseButtonCallback, CharCallback, SetKeyState, SetButtonState, GetMouseButtonState, GetKeyState)

## Tasks

- [ ] Implement RenderingTarget interface (based on the window, but has to fulfill the needs of the canvas also).
- [ ] Extend wrapper with the RenderingTarget.
- [ ] Eliminate the window from the Application package. Use the wrapper's RenderingTarget instead.
- [ ] Eliminate the glfw dependency from the Application package. (Input interface and package that holds this dependency. For wasm, it will be different.)
- [ ] Application New forces us to use the glfw stores. It has to be different for wasm build, so that this dependency has to be eliminated.
- [ ] Wasm rendering context implementation.
- [ ] Implement stores for wasm.
- [ ] Implement wasm wrapper.
